import React from 'react'
import Caramel from '../assets/images/crispy-caramel.png'
import Cocoa from '../assets/images/dark-cocoa.png'
import Orange from '../assets/images/orange-zest-milk.png'
import Almond from '../assets/images/almond-crunch.png'
